trigger: none
pr: none

name: publish-hive-jwt-auth-$(Date:yyyy-MM-dd)$(Rev:.r)

parameters:
- name: versionBump
  displayName: Version bump
  type: string
  values:
  - Major
  - Minor
  - Bugfix
  default: Minor
- name: isSnapshot
  displayName: Is snapshot?
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines
    type: github
    name: hivestreaming/azure-ci
    ref: refs/heads/PTF-2030_migrate-to-azure-ci
    #     ref: refs/heads/EE-1_my-awesome-feature # pin to a specific branch during development
    endpoint: hivestreaming  # Azure DevOps service connection.

extends:
  template: templates/npm/publish-library.yml@pipelines
  parameters:
    versionBump: ${{ parameters.versionBump }}
    isSnapshot: ${{ parameters.isSnapshot }}
    useExistingTag: false
    workingDirectory: nodejs
    prePublish:
    - template: templates/install.yml
