trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - template: templates/install.yml
  - task: Npm@1
    displayName: NPM Publish
    inputs:
      command: publish
      verbose: true
      publishEndpoint: npm registry
      workingDir: nodejs
