trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - template: templates/install.yml
  - task: Npm@1
    displayName: NPM Access
    inputs:
      command: custom
      customCommand: access public
      verbose: true
      customEndpoint: npm registry
      workingDir: nodejs
